name: ZAProxy scan
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan ZAP website
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: "ZAP API Scan Heroku App"
        uses: zaproxy/action-api-scan@v0.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://matias-armandola.herokuapp.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'   
